Mender state script: Fix issue when have both Nvidia boot slot active   with boot_successful:1
When perform an A/B system updates after a commit two nvidia slots are
active with boot_successful:1, after a several reboot, the nvidia slot
change from one to the other. Please see below the issue logs

https://github.com/OE4T/meta-tegra/issues/388#issuecomment-658400809

In this case, we should mark the unused slot as unbootable.

diff --git a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
--- a/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
+++ b/meta-mender-tegra/recipes-mender/tegra-state-scripts/files/redundant-boot-commit-check-script-uboot
@@ -31,4 +31,12 @@ if [ "${devnam##/dev/mmcblk}" != "${devnam}" ]; then
 	exit 1
     fi
 fi
+
+otherslot=`expr 1 - $curslot`
+if ! nvbootctrl set-slot-as-unbootable $otherslot; then
+    echo "ERR: could not set slot $otherslot as unbootable" >&2
+    exit 1
+fi
+echo "Marked boot slot $otherslot as unbootable"
+
 exit 0
